### PR TITLE
Fix typo in 'Your revision is building' message

### PR DESCRIPTION
**Pull request by mpetazzoni**
Mostly, `s/CirlceCI/CircleCI/`

### CODE REVIEW

**Comment by mpetazzoni** [comment]
@cep21 Let me know if anything needs to happen after this is merged to get it deployed.

**Comment by cep21** [comment]
The release process is to push this to the branch "release" (I will do that).  Circle will when build a docker image tagged latest (from branch release) and push that to quay which we can then redeploy w/ maestro.

**Comment by mpetazzoni** [comment]
Thanks. Are you taking care of it then?

**Comment by cep21** [comment]
yea

**Pull request merged**
